### ISSUE TITLE
make a command handler (and move all commands there)

### ISSUE THREAD

**Issue by stefa-n** [superstashed/medusa-stonkers#5]

**Comment by devcer** [comment]
Hey, Can you tell me what exactly is needed here, I can help with it.

**Comment by stefa-n** [comment]
> Hey, Can you tell me what exactly is needed here, I can help with it.

Hello! I need every command (except ticket ones for buttons) to be a separate file in a "commands" folder

**Comment by komen205** [comment]
Can I take this or already taken? @stefa-n
